### ISSUE TITLE
getUserById does not return a user object

### ISSUE THREAD

**Issue by swigstrom** [synapsepayments/SynapsePay-Node#7]
The getUserById method does not return a user object like the other methods in Users.js.

**Comment by teganduong** [comment]
Hi @swigstrom , we decided to remove the getUserById method from the library because it's a duplicate of Users.get with options and wasn't returning a user object like the other methods in Users.js as you mentioned. So just use Users.get and pass in an options object as shown in the example in samples.md. Sorry for the confusion!

**Comment by swigstrom** [comment]
Thanks for clarifying
